name: CI

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  commitlint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"
          cache: "npm"
      - name: Install dependencies
        run: |
          npm ci
      - name: Print versions
        run: |
          git --version
          node --version
          npm --version
          npx commitlint --version

    if: github.event_name == 'push'
    steps:
      - name: Validate current commit (last commit) with commitlint
        run: npx commitlint --from HEAD~1 --to HEAD --verbose

    if: github.event_name == 'pull_request'
    steps:
      - name: Validate PR commits with commitlint
        run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
      - name: Build site
        run: |
          npm run build
      - name: Lint site
        run: |
          npm run lint
      - name: Waiting for 200 from the Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@v1.4
        id: waitFor200
        with:
          site_name: "ovinhaca"
          max_timeout: 60
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v10
        with:
          urls: |
            ${{ steps.waitFor200.outputs.url }}
          budgetPath: ./budget.json
          uploadArtifacts: true
          temporaryPublicStorage: true
